name: FreeBSD CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up FreeBSD environment
      uses: vmactions/freebsd-vm@v1.0.8
      with:
        usesh: true
        sync: sshfs
        prepare: |
          pkg install -y elixir erlang
        run: |
          mix deps.get
          mix compile
          mix escript.build
          ./exfetch -h
