name: Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.2'
        otp-version: '26.2'

    - name: Get deps
      run: mix deps.get

    - name: Compile
      run: mix compile

    - name: Build escript
      run: mix escript.build

    - name: Run exfetch
      run: ./exfetch -h
