name: NetBSD CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  netbsd:
    runs-on: ubuntu-latest
    name: NetBSD CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up NetBSD environment
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        sync: sshfs
        prepare: |
          pkgin update
          pkgin -y install elixir

    - name: Set up PATH
      run: echo 'export PATH=$PATH:/usr/pkg/lib/erlang/bin' >> $GITHUB_ENV

    - name: Get deps
      run: mix compile
      
    - name: Compile
      run: mix compile

    - name: Build escript
      run: mix escript.build

    - name: Run exfetch
      run: ./exfetch -h
