name: OpenBSD CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  openbsd:
    runs-on: ubuntu-latest
    name: OpenBSD CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up OpenBSD environment
      uses: vmactions/openbsd-vm@v1.0.8
      with:
        usesh: true
        sync: sshfs
        prepare: |
          pkg_add elixir

    - name: Set up PATH
      run: echo 'export PATH=$PATH:/usr/local/lib/erlang25/bin' >> $GITHUB_ENV

    - name: Get deps
      run: mix deps.get
      
    - name: Compile
      run: mix compile

    - name: Build escript
      run: mix escript.build

    - name: Run exfetch
      run: ./exfetch -h
